"""followers

Revision ID: 023fe4dac389
Revises: a6cfaf4cd1ac
Create Date: 2023-04-11 08:10:30.980575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '023fe4dac389'
down_revision = 'a6cfaf4cd1ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
